version: '3'

services:
  denopaste:
    image: smelnicki/denopaste:latest
    container_name: denopaste
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - PIRSCH_HOSTNAME=${PIRSCH_HOSTNAME}
      - PIRSCH_TOKEN=${PIRSCH_TOKEN}
      - LITESTREAM_AZURE_ACCOUNT_KEY=${LITESTREAM_AZURE_ACCOUNT_KEY}
      - DB_REPLICA_URL=${DB_REPLICA_URL}
