services:
  denopaste:
    image: smelnicki/denopaste:latest
    container_name: denopaste
    restart: always
    environment:
      - LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}
      - LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}
      - DB_REPLICA_URL=${DB_REPLICA_URL}
    networks:
      - denopaste-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - denopaste
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - denopaste-network

networks:
  denopaste-network:
    driver: bridge
