version: '3'

services:
  denopaste:
    image: smelnicki/denopaste:latest
    container_name: denopaste
    ports:
      - "80:8000"
      - "443:8000"
    environment:
      - LITESTREAM_AZURE_ACCOUNT_KEY=${LITESTREAM_AZURE_ACCOUNT_KEY}
      - DB_REPLICA_URL=${DB_REPLICA_URL}
    restart: always
    