name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        deno: ["v1.x"]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        include:
        - os: ubuntu-latest
          cache_path: ~/.cache/deno/
        - os: macos-latest
          cache_path: ~/Library/Caches/deno/
        - os: windows-latest
          cache_path: ~\AppData\Local\deno\

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check project
        run: deno task check

      - name: Run tests
        run: deno task test